#!/bin/bash
# Generate a pomo status bar
# 󰪥 󰪤 󰪣 󰪢 󰪡 󰪠 󰪟 󰪞
#
# \udb82\udea5
# \udb82\udea4
# \udb82\udea3
# \udb82\udea2
# \udb82\udea1
# \udb82\udea0
# \udb82\ude9f
# \udb82\ude9e

set -e

status=$(pomo status)
if [[ $? -eq 1 ]] ; then
	exit 0
fi

count=$(echo $status | awk '{if ($1 == 0) {print "(1-"$2"/"$3") * 8;scale=0;last/1"} else {print "(1-"$2"/"$4") * 8;scale=0;last/1"}}' | bc -l | tail -1)

python3 -c "print((b'\xf3\xb0\xaa'+ bytes([0xa5-int($count)])).decode(), end='')"

