[window]
opacity = 0.95
startup_mode = "Fullscreen"

[colors.bright]
black = "#75715e"
blue = "#66d9ef"
cyan = "#a1efe4"
green = "#a6e22e"
magenta = "#ae81ff"
red = "#f92672"
white = "#f9f8f5"
yellow = "#f4bf75"

[colors.normal]
black = "#222222"
blue = "#3f76ce"
# brown = "#ff8080"
cyan = "#a1efe4"
# darkblue = "#106474"
# darkbrown = "#a4903D"
# darkcyan = "#20d9c2"
# darkgray = "#434343"
# darkgreen = "#029b1c"
# darkmagenta = "#972c97"
# darkred = "#79092f"
# darkyellow = "#d6cc00"
# gray = "#7d7d7d"
green = "#088001"
# lightblue = "#3a8998"
# lightcyan = "#66d9ef"
# lightgray = "#adafaf"
# lightgreen = "#a6e22e"
# lightmagenta = "#c72c77"
# lightpurple = "#ff80ff"
# lightred = "#f92042"
# lightyellow = "#e6db74"
magenta = "#a72c77"
# offblack = "#303044"
# orange = "#c94600"
# pink = "#fd0c70"
# purple = "#7d0c70"
red = "#f92672"
# seagreen = "#5e8b56"
# slateblue = "#6a5acd"
# specialcyan = "#078c8c"
# violet = "#af80ff"
yellow = "#e6db74"

[colors.primary]
background = "#161616"
foreground = "#adafaf"

[env]
TERM = "xterm-256color"

[font]
size = 15

[font.bold]
family = "CommitMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "CommitMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "CommitMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

#[light-theme.bright]
#black = "#75715e"
#blue = "#66d9ef"
#cyan = "#a1efe4"
#green = "#a6e22e"
#magenta = "#ae81ff"
#red = "#f92672"
#white = "#f9f8f5"
#yellow = "#f4bf75"
#
#[light-theme.normal]
#black = "#222222"
#blue = "#3f76ce"
#brown = "#ff8080"
#cyan = "#a1efe4"
#darkblue = "#106474"
#darkbrown = "#a4903D"
#darkcyan = "#20d9c2"
#darkgray = "#434343"
#darkgreen = "#029b1c"
#darkmagenta = "#972c97"
#darkred = "#79092f"
#darkyellow = "#d6cc00"
#gray = "#7d7d7d"
#green = "#088001"
#lightblue = "#3a8998"
#lightcyan = "#66d9ef"
#lightgray = "#adafaf"
#lightgreen = "#a6e22e"
#lightmagenta = "#c72c77"
#lightpurple = "#ff80ff"
#lightred = "#f92042"
#lightyellow = "#e6db74"
#magenta = "#a72c77"
#offblack = "#303044"
#orange = "#c94600"
#pink = "#fd0c70"
#purple = "#7d0c70"
#red = "#f92672"
#seagreen = "#5e8b56"
#slateblue = "#6a5acd"
#specialcyan = "#078c8c"
#violet = "#af80ff"
#yellow = "#e6db74"
#
#[light-theme.primary]
#background = "#f0f0f0"
#foreground = "#222222"
#
#[monocle.bright]
#black = "#75715e"
#blue = "#66d9ef"
#cyan = "#a1efe4"
#green = "#a6e22e"
#magenta = "#ae81ff"
#red = "#f92672"
#white = "#f9f8f5"
#yellow = "#f4bf75"
#
#[monocle.normal]
#black = "#222222"
#blue = "#3f76ce"
#brown = "#ff8080"
#cyan = "#a1efe4"
#darkblue = "#106474"
#darkbrown = "#a4903D"
#darkcyan = "#20d9c2"
#darkgray = "#434343"
#darkgreen = "#029b1c"
#darkmagenta = "#972c97"
#darkred = "#79092f"
#darkyellow = "#d6cc00"
#gray = "#7d7d7d"
#green = "#088001"
#lightblue = "#3a8998"
#lightcyan = "#66d9ef"
#lightgray = "#adafaf"
#lightgreen = "#a6e22e"
#lightmagenta = "#c72c77"
#lightpurple = "#ff80ff"
#lightred = "#f92042"
#lightyellow = "#e6db74"
#magenta = "#a72c77"
#offblack = "#303044"
#orange = "#c94600"
#pink = "#fd0c70"
#purple = "#7d0c70"
#red = "#f92672"
#seagreen = "#5e8b56"
#slateblue = "#6a5acd"
#specialcyan = "#078c8c"
#violet = "#af80ff"
#yellow = "#e6db74"
#
#[monocle.primary]
#background = "#161616"
#foreground = "#adafaf"
[bell]
animation = "EaseOutSine"
