
[window]
opacity = 0.95
startup_mode = "Fullscreen"

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.bold]
family = "CommitMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "CommitMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "CommitMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[bell]
animation = "EaseOutSine"

[general]
import = [
	"~/.config/alacritty/themes/monocle.toml"
]
